baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mastodon Api Compatibility'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'

[params]
themeVariant = ['light', 'dark']
themeVariantAuto = "light"
